MaquetteForAnaqsup.UI/Controllers/DataDashboardsController.cs
using MaquetteForAnaqsup.UI.ApiServices;
using MaquetteForAnaqsup.UI.Models.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using NuGet.Common;
using System.Data;
using System.Reflection;
using System.Security.Cryptography;

namespace MaquetteForAnaqsup.UI.Controllers
{
    public class DataDashboardsController : Controller
    {
        private readonly DataDashboardsApiService _apiServiceDataProcessing;

        public DataDashboardsController(DataDashboardsApiService apiServiceDataProcessing)
        {
            _apiServiceDataProcessing = apiServiceDataProcessing;
        }

        public async Task<IActionResult> Index()
        {
            var viewData = await _apiServiceDataProcessing.GetDropdownStatData();

            ViewData["CodeUniversite"] = new SelectList(viewData.DataUniversites, "CodeUniversite", "LibelleUniversite");
            //ViewData["Departement"] = new SelectList(viewData.DataDepartements, "Departement", "Departement");
            ViewData["Grade"] = new SelectList(viewData.DataGrades, "Grade", "Grade");
            ViewData["Niveau"] = new SelectList(viewData.DataNiveaus, "Niveau", "Niveau");
            ViewData["Semestre"] = new SelectList(viewData.DataSemestres, "Semestre", "Semestre");
            //ViewData["Abreviation"] = new SelectList(viewData.DataNiveaus, "Abreviation", "LibelleFormation");
            //ViewData["LibelleParcour"] = new SelectList(viewData.DataNiveaus, "LibelleParcour", "LibelleParcour");
            
            return View(await _apiServiceDataProcessing.GetAllData());
        }

        public async Task<IActionResult> GetStatComparaisonData()
        {
            var viewData = await _apiServiceDataProcessing.GetDropdownStatData();
            ViewData["CodeUniversite"] = new SelectList(viewData.DataUniversites, "CodeUniversite", "LibelleUniversite");
            ViewData["Grade"] = new SelectList(viewData.DataGrades, "Grade", "Grade");
            ViewData["Niveau"] = new SelectList(viewData.DataNiveaus, "Niveau", "Niveau");
            ViewData["Semestre"] = new SelectList(viewData.DataSemestres, "Semestre", "Semestre");

            //return View(await _apiServiceDataProcessing.GetStatComparaisonData());
            return View(await _apiServiceDataProcessing.GetAllData());
        }

        [HttpPost]
        public async Task<IActionResult> FilterParametre(string submitButton, List<string>? codeUnivs, string? grade, int? niveau, int? semestre)
        {
            if (codeUnivs == null || codeUnivs.Count == 0)
            {
                codeUnivs = null;
            }
            if (grade == null || grade.Contains("Grade"))
            {
                grade = null;
            }
            if (niveau == null || niveau == 0)
            {
                niveau = 0;
            }
            if (semestre == null || semestre == 0)
            {
                semestre = 0;
            }
            DataParameterDto dataParameter = new DataParameterDto
            {
                CodeUnivs = codeUnivs,
                Grade = grade,
                Niveau = niveau ?? 0,
                Semestre = semestre ?? 0
            };
            var viewData = await _apiServiceDataProcessing.GetDropdownStatData();
            ViewData["CodeUniversite"] = new SelectList(viewData.DataUniversites, "CodeUniversite", "LibelleUniversite", codeUnivs);
            ViewData["Grade"] = new SelectList(viewData.DataGrades, "Grade", "Grade", grade);
            ViewData["Niveau"] = new SelectList(viewData.DataNiveaus, "Niveau", "Niveau", niveau);
            ViewData["Semestre"] = new SelectList(viewData.DataSemestres, "Semestre", "Semestre", semestre);

            switch (submitButton)
            {
                case "Commun":
                    return View("GetStatComparaisonData", await _apiServiceDataProcessing.GetStatDataCommune(dataParameter));
                case "Different":
                    return View("GetStatComparaisonData", await _apiServiceDataProcessing.GetStatDataDifferente(dataParameter));
                default:
                    return View(await _apiServiceDataProcessing.GetAllData());
            }
        }


        public async Task<IActionResult> IndexSearch()
        {
            return View(await _apiServiceDataProcessing.GetAllStatDataSearch());
        }

        [HttpPost]
        public async Task<IActionResult> FilterByKeyWord(string? searchString)
        {
            if (string.IsNullOrEmpty(searchString))
            {
                ModelState.AddModelError("searchString", "La recherche est vide.");
                return View(await _apiServiceDataProcessing.GetAllStatDataSearch());
            }
            if (searchString?.Length < 3)
            {
                ModelState.AddModelError("searchString", "La recherche doit contenir au moins 3 caractères.");
                return View(await _apiServiceDataProcessing.GetAllStatDataSearch());
            }
            
            return View("IndexSearch", await _apiServiceDataProcessing.GetFilterDataSearch(searchString));
        }

        //public async Task<IActionResult> IndexFormationDifference()
        //{
        //    var viewData = await _apiServiceDataProcessing.GetDropdownStatData();

        //    ViewData["CodeUniversite"] = new SelectList(viewData.DataUniversites, "CodeUniversite", "LibelleUniversite");
        //    ViewData["Grade"] = new SelectList(viewData.DataGrades, "Grade", "Grade");
        //    ViewData["Niveau"] = new SelectList(viewData.DataNiveaus, "Niveau", "Niveau");
        //    ViewData["Semestre"] = new SelectList(viewData.DataSemestres, "Semestre", "Semestre");

        //    return View(await _apiServiceDataProcessing.GetAllData());
        //}




        public async Task<IActionResult> IndexBetweenFormInterne()
        {
            return View(await _apiServiceDataProcessing.GetAllData());
        }

        [HttpPost]
        public async Task<IActionResult> FilterSearch(string? codeUniv, string? dept, string? grade, string? formation, int? niveau, int? semestre, string? parcour)
        {
            var lstDatas = await _apiServiceDataProcessing.GetFilterInterneDeptData(codeUniv, dept, grade, formation, niveau, semestre, parcour);

            DataDashboardDto model = new DataDashboardDto();

            var viewData = await _apiServiceDataProcessing.GetDropdownStatData();
            ViewData["CodeUniversite"] = new SelectList(viewData.DataUniversites, "CodeUniversite", "LibelleUniversite", codeUniv);
            ViewData["dept"] = new SelectList(model.ListDepartements, "Departement", "Departement", dept);

            return View("Index", lstDatas);
        }


        [HttpPost]
        public async Task<IActionResult> FilterLstDept(string cid)
        {
            //codeUniv = cid;
            var lstDepartements = await _apiServiceDataProcessing.GetDropdownStatData();
            DataDashboardDto model = new DataDashboardDto();

            model.ListDepartements = lstDepartements.DataDepartements.Where(x => x.CodeUniversite == cid).ToList();

            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> FilterLstForm(string did, string cid)
        {
            //codeUniv = cid;
            var lstDepartements = await _apiServiceDataProcessing.GetDropdownStatData();
            DataDashboardDto model = new DataDashboardDto();

            model.ListFormations = lstDepartements.DataFormations.Where(x => x.Departement == did & x.CodeUniversite == cid).ToList();

            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> FilterLstGrade(string gid, string did, string cid)
        {
            //codeUniv = cid;
            var lstDepartements = await _apiServiceDataProcessing.GetDropdownStatData();
            DataDashboardDto model = new DataDashboardDto();
            if(gid.Contains("Selectionner "))
            {
                model.ListFormations = lstDepartements.DataFormations.Where(x => x.Departement == did & x.CodeUniversite == cid).ToList();
            }
            model.ListFormations = lstDepartements.DataFormations.Where(x => x.Grade == gid & x.Departement == did & x.CodeUniversite == cid).ToList();

            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> FilterLstNiveau(int nid, string fid, string gid, string did, string cid)
        {
            //codeUniv = cid;
            var lstDepartements = await _apiServiceDataProcessing.GetDropdownStatData();
            DataDashboardDto model = new DataDashboardDto();
            if (gid.Contains("Selectionner "))
            {
                model.ListParcours = lstDepartements.DataParcours.Where(x => x.Grade == gid & x.Departement == did & x.CodeUniversite == cid).ToList();
            }
            model.ListParcours = lstDepartements.DataParcours.Where(x => x.Niveau == nid & x.Abreviation == fid & x.Grade == gid & x.Departement == did & x.CodeUniversite == cid).ToList();

            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> FilterLstParcour(int nid, string fid, string gid, string did, string cid)
        {
            //codeUniv = cid;
            var lstDepartements = await _apiServiceDataProcessing.GetDropdownStatData();
            DataDashboardDto model = new DataDashboardDto();
            if (gid.Contains("Selectionner "))
            {
                model.ListParcours = lstDepartements.DataParcours.Where(x => x.Grade == gid & x.Departement == did & x.CodeUniversite == cid).ToList();
            }
            model.ListParcours = lstDepartements.DataParcours.Where(x => x.Niveau == nid & x.Abreviation == fid & x.Grade == gid & x.Departement == did & x.CodeUniversite == cid).ToList();

            return Json(model);
        }
    }
}

MaquetteForAnaqsup.UI/Views/DataDashboards/GetStatComparaisonData.cshtml
@using MaquetteForAnaqsup.UI.Models.DTO
@using Newtonsoft.Json
@model DataDashboardDto

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <h3 class="text-center">Filtre générique </h3>
                <div class="card-header">
                    <form asp-controller="DataDashboards" asp-action="FilterParametre" style="padding-right: 25px;">
                        <div class="row mt-2 mb-2">
                            <div class="col-md-6">
                                <select asp-for="CodeUniversite" name="codeUnivs" class="form-control select2" data-placeholder="Selectionner université" asp-items="ViewBag.CodeUniversite" multiple="multiple" style="width: 100%;">
                                </select>
                                <span asp-validation-for="CodeUniversite" class="text-danger"></span>
                            </div>
                            <div class="col-md-2">
                                <select asp-for="Grade" name="grade" class="form-control form-select" asp-items="ViewBag.Grade">
                                    <option>Grade ...</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <select asp-for="Niveau" name="niveau" class="form-control form-select" asp-items="ViewBag.Niveau">
                                    <option>Niveau ...</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <select asp-for="Semestre" name="semestre" class="form-control form-select" asp-items="ViewBag.Semestre">
                                    <option>Semestre ...</option>
                                </select>
                            </div>
                        </div>
                        <div class="row mt-2 mb-2">
                            <div class="col-md-12">
                                <div class="form-group mt-3 text-center">
                                    <input type="submit" name="submitButton" value="Commun" class="btn btn-success btn-lg p-3 mb-2" />
                                    <input type="submit" name="submitButton" value="Different" class="btn btn-danger btn-lg p-3 mb-2" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- AREA CHART -->
    <div class="row">
        <div class="col-md-12">
            
            <div class="card card-info">
                <div class="card-header">
                    <h1 class="card-title">@Model.LibelleViewData</h1>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="chart">
                        <canvas id="barChart" style="min-height: 500px; height: 500px; max-height: 500px; max-width: 100%;"></canvas>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">@Model.LibelleViewData</h1>
                </div>
                <div class="card-body">
                    <div class="table-responsive-sm">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CodeUniversite)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Departement)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Abreviation)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.LibelleFormation)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Grade)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Semestre)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Parcours)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Niveau)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CodeUE)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.LibelleUE)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CreditUE)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CoefUE)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CodeEC)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.LibelleLongEC)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CoefEC)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CM)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.TD)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.TP)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.SEM)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.ImportDatas)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CodeUniversite)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Departement)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Abreviation)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LibelleFormation)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Grade)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Semestre)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Parcours)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Niveau)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CodeUE)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LibelleUE)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CreditUE)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CoefUE)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CodeEC)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LibelleLongEC)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CoefEC)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CM)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TD)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TP)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SEM)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const ctx1 = document.getElementById('barChart');
    new Chart(ctx1, {
      type: 'bar',
      data: {
        labels: @Html.Raw(JsonConvert.SerializeObject(Model.StemmedTokens)),
        datasets: [{
          label: 'Formation',
          data: @Html.Raw(JsonConvert.SerializeObject(Model.FrequencyTokens)),
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });

</script>

MaquetteForAnaqsup.UI/Views/DataDashboards/IndexSearch.cshtml
@using MaquetteForAnaqsup.UI.Models.DTO
@using Newtonsoft.Json
@model DataDashboardDto

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center display-4">Filtrer pour améliorer le résultat</h2>
                    <div class="row">
                        <div class="col-md-8 offset-md-2">
                            <form asp-controller="DataDashboards" asp-action="FilterByKeyWord">
                                <div class="input-group">
                                <input name="searchString" type="search" class="form-control form-control-lg" placeholder="Rechercher par mot clés">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-lg btn-default">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- AREA CHART -->
    <div class="row mt-2">
        <div class="col-md-6">
            <div class="card card-info">
                <div class="card-header">
                    <h1 class="card-title">@Model.LibelleViewData</h1>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="chart">
                        <canvas id="barChart" style="min-height: 500px; height: 500px; max-height: 500px; max-width: 100%;"></canvas>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">@Model.LibelleViewData</h1>
                </div>
                <div class="card-body">
                    <div class="table-responsive-sm">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CodeUniversite)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Departement)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Abreviation)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.LibelleFormation)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Grade)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Semestre)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Parcours)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.Niveau)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.LibelleUE)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CreditUE)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.LibelleLongEC)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CoefEC)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.CM)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.TD)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.TP)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ImportData.SEM)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.ImportDatas)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CodeUniversite)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Departement)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Abreviation)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LibelleFormation)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Grade)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Semestre)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Parcours)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Niveau)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LibelleUE)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CreditUE)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LibelleLongEC)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CoefEC)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CM)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TD)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TP)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SEM)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const ctx1 = document.getElementById('barChart');
    new Chart(ctx1, {
      type: 'bar',
      data: {
        labels: @Html.Raw(JsonConvert.SerializeObject(Model.UnivECs)),
        datasets: [{
          label: 'Formation',
          data: @Html.Raw(JsonConvert.SerializeObject(Model.nbreEC)),
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });

</script>